name: Python Template CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'
          architecture: 'x64'
      - name: Install Virtual Environment
        run: |
          sudo apt-get update
          sudo apt-get install curl
          curl -sSL https://install.python-poetry.org | python -
      - name: Run Unit Tests
        run: |
          printenv
          "${HOME}/.poetry/bin/poetry" install
          "${HOME}/.poetry/bin/poetry" run pytest --cov=omni_model/src omni_model/tests/
